# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false

matrix:
  include:
  - os: linux
    env:
      - PYTHON_VER='3.5'
  - os: linux
    env:
      - PYTHON_VER='2.7'

before_install:

# Get local information about the machine
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - python -V

  - conda create -q -n p4env python=$PYTHON_VER psi4 scipy -c psi4
  - source activate p4env
  - conda list

  - pip install --upgrade pip setuptools

# Install various required modules
  - pip install pytest pytest-cov
  - pip install codecov

# Install the plugin locally
  - pip install -e .

script:
  - py.test -v --cov=./

# after_success:
#   - ./tools/travis-upload-wheel.sh

notifications:
    email: false

after_success:
  - codecov
